name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && github.event.pull_request.head.ref != 'version-bump' }}
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_URL: redis://localhost:6379

  publish:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && github.event.pull_request.head.ref != 'version-bump' }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: "npm"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Configure Git
        run: |
          git config --global user.email "balajijanarthanan1997@gmail.com"
          git config --global user.name "Balaji J"

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm with auto-version bump
        if: github.ref == 'refs/heads/main'
        run: |
          npm publish --access public || (
            echo "Version exists, bumping version..." &&
            npm version patch --no-git-tag-version &&
            git add package.json &&
            git commit -m "chore: bump version to $(npm version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" || echo "No changes to commit"
          )
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push and Create Pull Request
        run: |
          if git diff --exit-code; then
            echo "No changes to commit; skipping push and PR creation."
          else
            git push origin HEAD
            gh pr create --title "chore: bump version to $(npm version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" --body "Automatically bumped version to $(npm version)" --head HEAD --base main
          fi
