name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_URL: redis://localhost:6379

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: "npm"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Configure Git
        run: |
          git config --global user.email "balajijanarthanan1997@gmail.com"
          git config --global user.name "Balaji J"

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm with auto-version bump
        if: github.ref == 'refs/heads/main'
        run: |
          npm publish --access public || (
            echo "Version exists, bumping version..." &&
            npm version patch &&
            git checkout -b version-bump-$(date +%s) &&
            git add . &&
            git commit -m "chore: bump version to $(npm version)" &&
            git push origin HEAD &&
            gh pr create --title "chore: bump version to $(npm version)" --body "Automatically bumped version to $(npm version)" --head $(git rev-parse --abbrev-ref HEAD) --base main
          )
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version-bump:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Install dependencies
        run: npm install

      - name: Commit any changes
        run: |
          git config --global user.email "balajijanarthanan1997@gmail.com"
          git config --global user.name "Balaji J"
          git add .
          git commit -m "chore: commit changes before version bump" || echo "No changes to commit"

      - name: Bump version and create pull request
        if: github.ref == 'refs/heads/main'
        run: |
          npm version patch &&
          git checkout -b version-bump-$(date +%s) &&
          git add . &&
          git commit -m "chore: bump version to $(npm version)" &&
          git push origin HEAD &&
          gh pr create --title "chore: bump version to $(npm version)" --body "
