name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"  # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: build  # This ensures the publish job runs only if the build job is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci  # Using `npm ci` for clean install in CI environments

      - name: Publish to npm
        if: github.ref == 'refs/heads/main'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  version-bump:
    runs-on: ubuntu-latest
    needs: publish  # This ensures the version bump happens only after a successful publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Bump version and push tags
        if: github.ref == 'refs/heads/main'
        run: |
          npm version patch
          git push origin --tags
          git push origin main
